controllers:
    resource: ../src/Controller/
    type: annotation

static:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: default/index.html.twig

kernel:
    resource: ../src/Kernel.php
    type: annotation
